// 多智能体编排器
// 按序执行：数据解析 → 化学解释 → 教学设计 → 批改反馈
// 每个 Agent 的输出作为下一个 Agent 的上下文

import { DataParserAgent } from "./agents/data-parser.js";
import { ChemicalExplainerAgent } from "./agents/chemical-explainer.js";
import { TeachingDesignerAgent } from "./agents/teaching-designer.js";
import { GradingFeedbackAgent } from "./agents/grading-feedback.js";

export class Orchestrator {
  constructor(llm = null) {
    this.llm = llm;
    this.agents = [
      new DataParserAgent(llm),
      new ChemicalExplainerAgent(llm),
      new TeachingDesignerAgent(llm),
      new GradingFeedbackAgent(llm),
    ];
  }

  // ===== XYZ to PDB Converter =====
  // Generates PDB data with CONECT records for high-quality 3D visualization.
  // This data flows: Backend → Frontend Mol* renderer
  xyzToPdb(xyzText, title = "ChemClaw") {
    const atoms = this.parseXYZAtoms(xyzText);
    if (!atoms.length) return "";

    const bonds = this.computeBonds(atoms);
    const lines = [];
    lines.push(`HEADER    ${title}`);
    lines.push(`TITLE     ${title}`);
    lines.push(`REMARK   Generated by ChemClaw - ${atoms.length} atoms, ${bonds.length} bonds`);

    for (let i = 0; i < atoms.length; i++) {
      const [elem, x, y, z] = atoms[i];
      const serial = String(i + 1).padStart(5);
      const name = elem.padEnd(4);
      const xStr = x.toFixed(3).padStart(8);
      const yStr = y.toFixed(3).padStart(8);
      const zStr = z.toFixed(3).padStart(8);
      const element = elem.padStart(2);
      lines.push(`ATOM  ${serial} ${name} MOL A   1    ${xStr}${yStr}${zStr}  1.00  0.00          ${element}`);
    }

    // CONECT records
    const conectMap = {};
    for (const [i, j] of bonds) {
      (conectMap[i + 1] ??= []).push(j + 1);
      (conectMap[j + 1] ??= []).push(i + 1);
    }
    for (const [atomSerial, connected] of Object.entries(conectMap)) {
      const sorted = [...new Set(connected)].sort((a, b) => a - b);
      for (let k = 0; k < sorted.length; k += 4) {
        const chunk = sorted.slice(k, k + 4);
        lines.push(`CONECT${String(atomSerial).padStart(5)}${chunk.map(c => String(c).padStart(5)).join("")}`);
      }
    }
    lines.push("END");
    return lines.join("\n");
  }

  parseXYZAtoms(text = "") {
    const lines = text.trim().split(/\r?\n/);
    const start = /^\d+$/.test(lines[0]?.trim()) ? 2 : 0;
    const atoms = [];
    for (const line of lines.slice(start)) {
      const parts = line.trim().split(/\s+/);
      if (parts.length >= 4 && /^[A-Z][a-z]?$/.test(parts[0])) {
        const x = Number(parts[1]), y = Number(parts[2]), z = Number(parts[3]);
        if (Number.isFinite(x) && Number.isFinite(y) && Number.isFinite(z)) {
          atoms.push([parts[0], x, y, z]);
        }
      }
    }
    return atoms;
  }

  computeBonds(atoms) {
    const radii = { H: 0.31, C: 0.76, N: 0.71, O: 0.66, F: 0.57, S: 1.05, P: 1.07, Cl: 1.02, Br: 1.20, I: 1.39 };
    const bonds = [];
    for (let i = 0; i < atoms.length; i++) {
      for (let j = i + 1; j < atoms.length; j++) {
        const dx = atoms[i][1] - atoms[j][1], dy = atoms[i][2] - atoms[j][2], dz = atoms[i][3] - atoms[j][3];
        const dist = Math.sqrt(dx * dx + dy * dy + dz * dz);
        const r1 = radii[atoms[i][0]] || 0.76, r2 = radii[atoms[j][0]] || 0.76;
        if (dist > 0.25 && dist < (r1 + r2) * 1.28) bonds.push([i, j]);
      }
    }
    return bonds;
  }

  async runAnalysis({ datasetName = "unknown", datasetText = "", moleculeText = "" }) {
    const context = {
      raw: { datasetName, datasetText, moleculeText },
      startedAt: new Date().toISOString()
    };

    const agentResults = [];

    // Agent 1: 数据解析
    const parseResult = await this.agents[0].analyze(context);
    Object.assign(context, { metrics: parseResult.metrics, parsed: parseResult.parsed });
    agentResults.push({ agent: parseResult.agent, finding: parseResult.findings, warnings: parseResult.warnings });

    // Agent 2: 化学解释
    const explainResult = await this.agents[1].analyze(context);
    Object.assign(context, { explanations: explainResult.explanations });
    agentResults.push({ agent: explainResult.agent, finding: explainResult.summary, explanations: explainResult.explanations });

    // Agent 3: 教学设计
    const teachResult = await this.agents[2].analyze(context);
    Object.assign(context, { teaching: teachResult });
    agentResults.push({ agent: teachResult.agent, finding: teachResult.learningPath?.[0] || "学习路径已生成", teaching: teachResult });

    // 组装结果 (不含批改)
    const metrics = parseResult.metrics || {};
    const imagCount = metrics.imaginaryFrequencies?.length || 0;
    const hasReactionPath = (metrics.energies?.length || 0) > 1 || metrics.barrier !== undefined;
    const barrier = hasReactionPath ? (metrics.barrier ?? metrics.energySpan ?? null) : null;
    const gap = Number.isFinite(metrics.gap) ? metrics.gap : null;
    const adsorption = metrics.adsorption;
    const chart = this.buildChart(metrics, barrier);
    const structures = this.buildStructureFrames(metrics, moleculeText);
    const optimizationTrajectory = this.buildOptimizationTrajectory(metrics, structures);
    const fileDetails = {
      ...(metrics.fileDetails || {}),
      structureFrameCount: Math.max(metrics.fileDetails?.structureFrameCount || 0, structures.length)
    };

    // Generate PDB data for 3D visualization (OpenClaw provides structured data)
    const moleculeXYZ = moleculeText?.trim() || structures[0]?.xyz || "";
    const pdbData = moleculeXYZ ? this.xyzToPdb(moleculeXYZ, this.inferTitle(metrics, datasetName)) : "";

    return {
      mode: this.llm ? "ai-agent" : "local-demo",
      model: this.llm?.model || null,
      datasetName,
      projectTitle: this.inferTitle(metrics, datasetName),
      summary: this.buildSummary(metrics, imagCount, teachResult),
      metrics: {
        calculationType: metrics.calculationType || "通用计算",
          scfEnergy: metrics.scfEnergy,
        ...(barrier !== null ? { activationBarrier: `${barrier} kcal/mol` } : {}),
        ...(gap !== null ? { homoLumoGap: `${gap} eV` } : {}),
        imaginaryFrequency: imagCount > 0 ? `${metrics.imaginaryFrequencies[0]} cm⁻¹` : "未检出",
        ...(adsorption !== undefined ? { adsorptionEnergy: `${adsorption} eV` } : {}),
        ...(metrics.thermo?.zpe != null ? { zeroPointEnergy: `${metrics.thermo.zpe.toFixed(6)} Hartree` } : {}),
        ...(metrics.thermo?.enthalpy != null ? { enthalpy: `${metrics.thermo.enthalpy.toFixed(6)} Hartree` } : {}),
        ...(metrics.thermo?.gibbs != null ? { gibbsFreeEnergy: `${metrics.thermo.gibbs.toFixed(6)} Hartree` } : {}),
        confidence: metrics.normalTermination ? "高" : "中"
      },
      chart,
      fileDetails,
      structures,
      basicInfo: this.buildBasicInfo(metrics, datasetName),
      optimizationProfile: this.buildOptimizationProfile(metrics, optimizationTrajectory),
      optimizationTrajectory,
      vibrationalProfile: this.buildVibrationalProfile(metrics),
      agentFindings: agentResults,
      learningPath: teachResult.learningPath || [],
      learningGoals: teachResult.learningGoals || [],
      quiz: teachResult.quiz || [],
      researchSuggestions: teachResult.researchSuggestions || [],
      literatureBenchmarks: teachResult.literatureBenchmarks || [],
      pdbData,
      openclawDataProvided: false,
      architecture: [
        { layer: "数据层", items: ["Gaussian/ORCA/VASP 输出", "CSV/XYZ 结构文件", "学生实验报告"] },
        { layer: "工具层", items: ["格式解析器", "能量/频率抽取", "3D 结构渲染", "报告结构识别"] },
        { layer: "智能体层", items: ["数据解析 Agent", "化学解释 Agent", "教学设计 Agent", "批改反馈 Agent"] },
        { layer: "教学层", items: ["学习目标映射", "自动出题", "Rubric 批改", "科研路径建议"] }
      ],
      nextSteps: [
        "加入 Gaussian/ORCA/VASP 输出文件的专用解析器",
        "将课程知识点映射到题库标签体系",
        "接入 OpenClaw 插件工具链，实现多智能体可视化编排"
      ]
    };
  }

  async runGrading({ studentReport = "", analysisContext = {} }) {
    const context = {
      raw: { studentReport },
      metrics: analysisContext.metrics || {},
      explanations: analysisContext.explanations || [],
      startedAt: new Date().toISOString()
    };

    const gradeResult = await this.agents[3].analyze(context);
    return {
      mode: this.llm ? "ai-agent" : "local-demo",
      model: this.llm?.model || null,
      agentFindings: [{
        agent: gradeResult.agent,
        finding: `报告评分: ${gradeResult.grading?.score ?? "未评分"}`,
        grading: gradeResult
      }],
      grading: gradeResult.grading || {},
      rubric: gradeResult.rubric || []
    };
  }

  inferTitle(metrics, datasetName) {
    if (datasetName && !datasetName.startsWith("sample")) return datasetName;
    if (metrics.imaginaryFrequencies?.length > 0) return "基于过渡态分析的反应机理研究";
    if (metrics.adsorption) return "表面吸附与催化活性计算研究";
    return "计算化学结构性质与反应性研究";
  }

  buildSummary(metrics, imagCount, teachResult) {
    const parts = [];
    if (metrics.calculationType) parts.push(`计算类型: ${metrics.calculationType}`);
    if (metrics.frequencies?.length > 0) parts.push(`包含 ${metrics.frequencies.length} 个频率模式`);
    if (imagCount > 0) parts.push(`检出 ${imagCount} 个虚频信号`);
    if (metrics.homo !== undefined) parts.push(`HOMO-LUMO gap 已计算`);
    parts.push(`生成 ${teachResult.quiz?.length || 0} 道训练题`);
    return parts.join("；");
  }

  buildChart(metrics, barrierFallback) {
    if (metrics.energies?.length > 1) {
      const min = Math.min(...metrics.energies.map(item => item.hartree));
      return {
        labels: metrics.energies.map(item => item.label),
        values: metrics.energies.map(item => Number(((item.hartree - min) * 627.509).toFixed(2))),
        unit: "kcal mol⁻¹"
      };
    }
    if (barrierFallback !== null && barrierFallback !== undefined) {
      return { labels: ["反应物", "过渡态"], values: [0, Number(barrierFallback)], unit: "kcal mol⁻¹" };
    }
    return { labels: [], values: [], unit: "kcal mol⁻¹", note: "当前输入只包含单个结构或未识别到反应路径，暂不绘制相对能量曲线。" };
  }

  buildStructureFrames(metrics, moleculeText = "") {
    if (metrics.structureFrames?.length) return metrics.structureFrames;
    if (moleculeText?.trim()) {
      const lines = moleculeText.trim().split(/\r?\n/);
      const atomCount = Number(lines[0]);
      if (Number.isFinite(atomCount)) {
        return [{ title: lines[1] || "输入 XYZ 结构", atomCount, xyz: moleculeText.trim() }];
      }
    }
    return [];
  }

  buildBasicInfo(metrics, datasetName) {
    return {
      software: metrics.fileDetails?.format === "gaussian" ? "Gaussian" : metrics.fileDetails?.format === "orca" ? "ORCA" : "未知",
      fileName: datasetName,
      taskType: metrics.calculationType || "未知任务",
      method: metrics.method || null,
      basis: metrics.basis || null,
      route: metrics.route || null,
      chargeMultiplicity: metrics.charge !== null && metrics.charge !== undefined ? `${metrics.charge} / ${metrics.multiplicity ?? "-"}` : null,
      outputCount: metrics.fileDetails?.energyPointCount || 0,
      normalTermination: metrics.normalTermination
    };
  }

  buildOptimizationProfile(metrics, trajectory = []) {
    if (trajectory.length > 1) {
      const values = trajectory.map(point => point.energyHartree).filter(Number.isFinite);
      return {
        steps: trajectory.map(point => point.step),
        values: trajectory.map(point => point.energyHartree),
        relativeValues: trajectory.map(point => point.relativeEnergyKcal),
        unit: "Hartree",
        hasStructures: trajectory.some(point => point.xyz),
        warnings: trajectory.warnings || []
      };
    }
    const points = metrics.optimizationEnergies || [];
    if (!points.length) return { steps: [], values: [], unit: "Hartree", note: "当前输入未识别到几何优化过程能量。" };
    return {
      steps: points.map(item => item.step),
      values: points.map(item => item.hartree),
      unit: "Hartree"
    };
  }

  buildOptimizationTrajectory(metrics, structures = []) {
    const energyPoints = metrics.optimizationEnergies || [];
    const hasOptimizationSignal = energyPoints.length > 1 || structures.length > 1;
    if (!hasOptimizationSignal) return [];

    const count = Math.max(energyPoints.length, structures.length);
    const finiteEnergies = energyPoints.map(point => point.hartree).filter(Number.isFinite);
    const minEnergy = finiteEnergies.length ? Math.min(...finiteEnergies) : null;
    const warnings = [];

    if (energyPoints.length > 1 && structures.length > 1 && energyPoints.length !== structures.length) {
      warnings.push(`优化能量点 ${energyPoints.length} 个，结构帧 ${structures.length} 个，已按顺序进行近似配对。`);
    }

    const pickStructure = (index) => {
      if (!structures.length) return { frame: null, frameIndex: null };
      if (count === structures.length) return { frame: structures[index], frameIndex: index };
      const mapped = Math.round((index / Math.max(count - 1, 1)) * (structures.length - 1));
      return { frame: structures[mapped], frameIndex: mapped };
    };

    const trajectory = Array.from({ length: count }, (_, index) => {
      const energy = energyPoints[index] || null;
      const { frame, frameIndex } = pickStructure(index);
      const energyHartree = Number.isFinite(energy?.hartree) ? energy.hartree : null;
      return {
        step: energy?.step ?? index + 1,
        energyHartree,
        relativeEnergyKcal: energyHartree !== null && minEnergy !== null
          ? Number(((energyHartree - minEnergy) * 627.509).toFixed(3))
          : null,
        frameIndex,
        title: `优化步 ${energy?.step ?? index + 1}`,
        structureTitle: frame?.title || null,
        atomCount: frame?.atomCount || null,
        xyz: frame?.xyz || null
      };
    });
    trajectory.warnings = warnings;
    return trajectory;
  }

  buildVibrationalProfile(metrics) {
    const modes = metrics.vibrationalModes || [];
    if (!modes.length) return { modes: [], note: "当前输入未识别到振动模式或 IR 强度。" };
    return {
      modes: modes.slice(0, 120),
      hasImaginary: modes.some(mode => mode.frequency < 0),
      unit: "cm⁻¹"
    };
  }
}
